version: '2'

networks:
  front:
  back:

services:
  mt:
    build: docker/mt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/movabletype:/app/movabletype
      - ./app/run:/app/run
      - ./data/file/static:/data/file/static
    networks:
      - front
      - back
    depends_on:
      - mysql

  apache:
    image: php:5.5-apache
    command: bash -c "a2enmod proxy proxy_http && apache2-foreground"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/movabletype/mt-static:/var/www/mt-static:ro
      - ./data/file/static:/var/www/html:ro
      - ./app/initial/etc/apache2/site-enabled:/etc/apache2/sites-enabled:ro
    networks:
      - front
    ports:
      - 80:80
    depends_on:
      - mt

  mysql:
    image: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "movabletype"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - back

