version: '2'

networks:
  front:
  back:

services:
  mt:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./site:/site
      - ./pid:/pid
      - ./movabletype:/mt
    networks:
      - front
      - back
    ports:
      - 3000:3000

  apache:
    build: docker/apache
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./movabletype/mt-static:/var/www/mt-static:ro
      - ./site:/var/www/html:ro
    networks:
      - front
    ports:
      - 80:80

#  nginx:
#    image: nginx:alpine
#    volumes:
#      - /etc/localtime:/etc/localhost:ro
#    networks:
#      - front
#    ports:
#      - 80:80

  mysql:
    image: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - back
    ports:
      - 3306:3306

#  postgres:
#    image: postgres
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      - back
#    ports:
#      - 5432:5432

  memcached:
    image: memcached:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - back
    ports:
      - 11211:11211

