version: '2'

networks:
  front:
  back:

services:
  mt:
    build: docker/mt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/movabletype:/app/movabletype
      - ./app/run:/app/run
      - ./data/file/static:/data/file/static
    networks:
      - front
      - back
    ports:
      - 3000:3000
    depends_on:
      - mysql

  apache:
    build: docker/apache
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app/movabletype/mt-static:/var/www/mt-static:ro
      - ./data/file/static:/var/www/html:ro
    networks:
      - front
    ports:
      - 80:80
    depends_on:
      - mt

#  nginx:
#    image: nginx:alpine
#    volumes:
#      - /etc/localtime:/etc/localhost:ro
#    networks:
#      - front
#    ports:
#      - 80:80

  mysql:
    image: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "movabletype"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - back
    ports:
      - 3306:3306

#  postgres:
#    image: postgres
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      - back
#    ports:
#      - 5432:5432

#  memcached:
#    image: memcached:alpine
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      - back
#    ports:
#      - 11211:11211

