version: "2"

services:
  apache:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./www/html:/var/www/html
      - ./www/cgi-bin:/usr/lib/cgi-bin
    ports:
      - 8080:80

