version: "3"

services:
  apache:
    build: .
    volumes:
      - ./html:/var/www/html
      - ./movabletype:/var/www/html/mt
    environment:
      MT_TEST_DBHost: "mysql"
    working_dir: /var/www/html/mt
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mt"

