version: '3'

networks:
  front:
  back:

services:
  apache:
    image: php:5.5-apache
    command: bash -c "a2enmod proxy proxy_http && apache2-foreground"
    volumes:
      - ./movabletype/mt-static:/var/www/mt-static:ro
      - ./html:/var/www/html:ro
      - ./conf:/etc/apache2/sites-enabled:ro
    networks:
      - front
    ports:
      - 8080:80
    depends_on:
      - mt

  mt:
    build: .
    volumes:
      - ./movabletype:/mt
      - ./html:/var/www/html
    networks:
      - front
      - back
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mt"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - back

