version: '3'

networks:
  front:
  back:

services:
  apache:
    image: ${PHP_APACHE_IMAGE}
    command: bash -c "a2enmod proxy proxy_http && apache2-foreground"
    volumes:
      - ./movabletype/mt-static:/var/www/mt-static:ro
      - ./html:/var/www/html:ro
      - ./conf:/etc/apache2/sites-enabled:ro
    networks:
      - front
    ports:
      - 8080:80
    depends_on:
      - mt

  mt:
    image: masiuchi/docker-mt-base:psgi
    command: bash -c "start_server --port=3000 --pid-file=mt.pid -- plackup -r -R ./plugins -R ./tools -s Starlet --max-workers=2 mt.psgi"
    volumes:
      - ./movabletype:/mt
      - ./html:/var/www/html
    networks:
      - front
      - back
    depends_on:
      - mysql

  mysql:
    image: ${MYSQL_IMAGE}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mt"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - back

