version: "3"

services:
  apache:
    image: masiuchi/docker-mt-base:cgi-dev
    volumes:
      - ./html:/var/www/html
      - ./movabletype:/var/www/html/mt
    environment:
      PERL_TEST_MYSQLPOOL_DSN: "DBI:mysql:host=mysql;user=root"
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mt"

